name:                graph-algorithms
version:             0.1.0.0
github:              "githubuser/graph-algorithms"
license:             BSD3
author:              "Jo Hsi"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/graph-algorithms#readme>

dependencies:
- base >= 4.7 && < 5
- fgl
- graphviz
- text
- pretty-simple

library:
  source-dirs: src

# executables:
#  graph-algorithms-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - graph-algorithms

tests:
  graph-algorithms-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graph-algorithms
