name:                quickcheck-rabbithole
version:             0.1.0.0
github:              "githubuser/quickcheck-rabbithole"
license:             BSD3
author:              "Jo Hsi"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/quickcheck-rabbithole#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- checkers

library:
  source-dirs: src

tests:
  quickcheck-rabbithole-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quickcheck-rabbithole
